version: "3.9"

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_DATABASE: TESTDB
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata

  php:
    image: jorgeingresa/ingresa:8.2
    container_name: php-oracle
    ports:
      - "8080:80"
    volumes:
      - ./php/index.php:/var/www/html/index.php
    environment:
      DB_USER: system
      DB_PASS: oracle
      DB_HOST: oracle
      DB_PORT: 1521
    depends_on:
      - oracle

volumes:
  oracle_data:
